config/routes.rb
ActiveInvoices::Application.routes.draw do
  get "welcome/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  
  root :to => "welcome#index"

  match 'quotation/:id/pdf' => 'quotation#view'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :expenses
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :invoices, :dependent => :destroy
  has_many :quotations, :dependent => :destroy
  
  validates :name, :presence => true
  validates :email, :format => { :with => /^(.+@.+\..+)?$/, :message => "is not a valid email address." }
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :admin_user
  validates :detail, :admin_user_id,:cost,:expense_type, :presence => true
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  STATUS_DRAFT = 'draft'
  STATUS_SENT  = 'sent'
  STATUS_PAID  = 'paid'
  
  belongs_to :client
  belongs_to :quotation
  has_many :items, :dependent => :destroy
  
  accepts_nested_attributes_for :items, :allow_destroy => true
  
  validates :code, :client_id,:due_date, :presence => true
  validates :status, :inclusion => { :in => [STATUS_PAID, STATUS_SENT, STATUS_DRAFT], :message => "You need to pick one status." }
  validates :tax, :discount, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100 }
  
  class << self
    def suggest_code
      invoice = order('created_at desc').limit(1).first
      if invoice
        "INV-#{invoice.id + 1}"
      else
        "INV-1"
      end
    end

    def status_collection
      {
        "Draft" => STATUS_DRAFT,
        "Sent" => STATUS_SENT,
        "Paid" => STATUS_PAID
      }
    end
    
    def this_month
      where('created_at >= ?', Date.new(Time.now.year, Time.now.month, 1).to_datetime)
    end
  end
  
  def items_total
    items_total = 0
    self.items.each do |i|
      items_total += i.total
    end
    items_total
  end
  
  def total
    items_total * (1 - self.discount / 100) * (1 + self.tax / 100)
  end
  
  def subtotal
    items_total * (1 - self.discount / 100)
  end
  
  def taxes
    subtotal * (self.tax / 100)
  end
  
  def status_tag
    case self.status
      when STATUS_DRAFT then :error
      when STATUS_SENT then :warning
      when STATUS_PAID then :ok
    end
  end
  
  def invoice_location
    "#{Rails.root}/pdfs/invoice-#{self.code}.pdf"
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :invoice
  
  validates :quantity, :presence => true, :numericality => { :integer => true }
  validates :amount, :presence => true, :numericality => true
  validates :description, :presence => true
  
  def total
    self.quantity * self.amount
  end
end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
  STATUS_DRAFT = 'draft'
  STATUS_SENT  = 'sent'
  STATUS_ACCEPTED  = 'accepted'
  
  belongs_to :client
  has_many :invoices
  has_many :quotation_items, :dependent => :destroy
  
  accepts_nested_attributes_for :quotation_items, :allow_destroy => true
  
  validates :code, :client_id, :presence => true
  validates :status, :inclusion => { :in => [STATUS_ACCEPTED, STATUS_SENT, STATUS_DRAFT], :message => "You need to pick one status." }
  validates :tax, :discount, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100 }
  
  class << self
    def suggest_code
      quotation = order('created_at desc').limit(1).first
      if quotation
        "INV-#{quotation.id + 1}"
      else
        "INV-1"
      end
    end

    def status_collection
      {
        "Draft" => STATUS_DRAFT,
        "Sent" => STATUS_SENT,
        "Paid" => STATUS_ACCEPTED
      }
    end
    
    def this_month
      where('created_at >= ?', Date.new(Time.now.year, Time.now.month, 1).to_datetime)
    end
  end
  
  def quotation_items_total
    quotation_items_total = 0
    self.quotation_items.each do |i|
      quotation_items_total += i.total
    end
    quotation_items_total
  end
  
  def total
    quotation_items_total * (1 - self.discount / 100) * (1 + self.tax / 100)
  end
  
  def subtotal
    quotation_items_total * (1 - self.discount / 100)
  end
  
  def to_s
    self.code
  end

  def taxes
    subtotal * (self.tax / 100)
  end
  
  def status_tag
    case self.status
      when STATUS_DRAFT then :error
      when STATUS_SENT then :warning
      when STATUS_ACCEPTED then :ok
    end
  end
  
  def quotation_location
    "#{Rails.root}/pdfs/quotation-#{self.code}.pdf"
  end
end

app/models/quotation_item.rb
class QuotationItem < ActiveRecord::Base
  belongs_to :quotation
  
  validates :quantity, :presence => true, :numericality => { :integer => true }
  validates :amount, :presence => true, :numericality => true
  validates :description, :presence => true
  
  def total
    self.quantity * self.amount
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to new_admin_user_session_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/invoices/send_invoice.html.erb
<%
invoice_message = <<MSG



-----------------------------
Invoice Summary
-----------------------------

Invoice Code: #{@invoice.code}
Due: #{l @invoice.due_date, :format => :short}
Amount: #{number_to_currency(@invoice.total,:locale => :th)}


Thank You!
-----------------------------

MSG
%>

<%= form_tag dispatch_invoice_admin_invoice_path(@invoice) do %>
  <fieldset class="inputs">
    <legend><span>Recipients</span></legend>
    <ol>
      <li class="string required">
        <%= label_tag :recipients %>
        <%= text_field_tag :recipients, @invoice.client.email %>
        <p class="inline-hints">Comma-separated list of emails.</p>
      </li>
      
      <li class="boolean">
        <label for="send_copy">
          <%= check_box_tag :send_copy, "send" %>
          Send me a copy
        </label>
      </li>
    </ol>
  </fieldset>
  
  <fieldset class="inputs">
    <legend><span>Message</span></legend>
    <ol>
      <li class="string required">
        <%= label_tag :subject %>
        <%= text_field_tag :subject, "Invoice ##{@invoice.code}" %>
      </li>
      
      <li class="textarea required">
        <%= label_tag :message %>
        <%= text_area_tag :message, invoice_message, :rows => 10 %>
      </li>
      
      <li class="boolean">
        <label for="attach_pdf">
          <%= check_box_tag :attach_pdf, "attach", true %>
          Attach Invoice as PDF
        </label>
      </li>
    </ol>
  </fieldset>
  
  <fieldset class="buttons">
    <ol>
      <li class="commit">
        <%= submit_tag "Send Invoice" %>
      </li>
      <li class="cancel">
        <%= link_to "Cancel", admin_invoice_path(@invoice) %>
      </li>
    </ol>
  </fieldset>
<% end %>

app/views/admin/quotations/send_quotation.html.erb
<%
quotation_message = <<MSG



-----------------------------
Quotation Summary
-----------------------------

Quotation Code: #{@quotation.code}
Amount: #{number_to_currency(@quotation.total,:locale => :th)}


Thank You!
-----------------------------

MSG
%>

<%= form_tag dispatch_quotation_admin_quotation_path(@quotation) do %>
  <fieldset class="inputs">
    <legend><span>Recipients</span></legend>
    <ol>
      <li class="string required">
        <%= label_tag :recipients %>
        <%= text_field_tag :recipients, @quotation.client.email %>
        <p class="inline-hints">Comma-separated list of emails.</p>
      </li>
      
      <li class="boolean">
        <label for="send_copy">
          <%= check_box_tag :send_copy, "send" %>
          Send me a copy
        </label>
      </li>
    </ol>
  </fieldset>
  
  <fieldset class="inputs">
    <legend><span>Message</span></legend>
    <ol>
      <li class="string required">
        <%= label_tag :subject %>
        <%= text_field_tag :subject, "Quotation ##{@quotation.code}" %>
      </li>
      
      <li class="textarea required">
        <%= label_tag :message %>
        <%= text_area_tag :message, quotation_message, :rows => 10 %>
      </li>
      
      <li class="boolean">
        <label for="attach_pdf">
          <%= check_box_tag :attach_pdf, "attach", true %>
          Attach Quotation as PDF
        </label>
      </li>
    </ol>
  </fieldset>
  
  <fieldset class="buttons">
    <ol>
      <li class="commit">
        <%= submit_tag "Send Quotation" %>
      </li>
      <li class="cancel">
        <%= link_to "Cancel", admin_quotation_path(@quotation) %>
      </li>
    </ol>
  </fieldset>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActiveInvoices</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>